### PR TITLE
Update originalCode.js

### PR DESCRIPTION
**Pull request by KnightBits**

### CODE REVIEW

**Comment by KnightBits** [comment]
**Description:**

This pull request introduces an improvement to the image loading mechanism in the printing functionality. Instead of using a polling interval to check for image loading, it utilizes a MutationObserver. This change enhances efficiency and resource utilization by allowing the code to react only when changes in the DOM occur, rather than constantly polling it at intervals.

**Changes:**

- Replaced interval-based image loading check with MutationObserver.
- Enhanced efficiency and resource management by reacting to DOM changes instead of polling.

**Benefits:**

- Improved performance and resource utilization.
- Cleaner and more responsive codebase.

This change is intended to optimize the image loading process, particularly in scenarios where there are frequent changes to the DOM structure

**Review by AnsonLai — APPROVED** [review]
Works for me, this is great!

**Comment by NightWolf1298** [comment]
Unfortunately this change no longer works for me. I am on Chrome 125.0.6422.61 (Official Build) (x86_64), and have tried with and without UBlock Origin enabled.

https://musescore.com/user/36902825/scores/7515920

With the new version (starting at 749a6af1e15539bdff7bc59fa85c7e0faa0c6ba8), the score area turns blank, then I get a timeout:
image

I went back to the code in 44f8bd35af0848619a0b40e90d30bab73bfb462a from 2023, copy/pasted the whole thing into the console, and that worked perfectly fine (with UBlock Origin enabled, if that matters):
image

**Comment by cirex-web** [comment]
> Awesome project by the way, I've used this several times while starting to learn piano and it's been super helpful to have the scores available as simple PDFs I can annotate and take with me!


❤️
\- the author of one of the earlier versions of this piece of code

**Comment by AnsonLai** [comment]
I did some testing and it looks like the new code only works if you tap the area outside of console or else it'll wait forever.  I like the approach to be honest, but I'll revert it back to the old version in the interest of making this as easy as possible for folks.

**Comment by KnightBits** [comment]
> I did some testing and it looks like the new code only works if you tap the area outside of console or else it'll wait forever. I like the approach to be honest, but I'll revert it back to the old version in the interest of making this as easy as possible for folks.

However, there are many other improvements. Maybe not return to the old version, but just add some changes? @AnsonLai

**Pull request merged**
