### PR TITLE
Update originalCode.js

### PR DESCRIPTION
**Pull request by KnightBits**
Updates have been made to improve reliability and security:
- Added a try...catch block to handle errors during script execution.
- Added a timeout for waiting for images to load to avoid endless waiting.
- Added messages to the console to track the status of image loading.

### CODE REVIEW

**Comment by KnightBits** [comment]
Updates have been made to improve reliability and security:

- Added a try...catch block to handle errors during script execution.
- Added a timeout for waiting for images to load to avoid endless waiting.
- Added messages to the console to track the status of image loading.

**Comment by AnsonLai** [comment]
Thanks for the contributions!!

**Comment by cirex-web** [comment]
omg this is still alive!

**Comment by KnightBits** [comment]
> omg this is still alive!

Ye. Make some fixes

**Pull request merged**
